kontenjan/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name= "kontenjan"



urlpatterns = [
    path('kontenjan/', views.kontenjan,name= "kontenjan"), 
    path('ebe21/', views.ebe21,name= "ebe21"), 
    path('hemsire21/', views.hemsire21,name= "hemsire21"), 
]

nick/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name= "nick"



urlpatterns = [
    path('dashboard/', views.dashboard,name= "dashboard"),
    path('addnick/', views.addnick,name= "addnick"),    
    path('nick/<int:id>/', views.detail,name= "detail"), 
    path('update/<int:id>/', views.update,name= "update"),   
    path('delete/<int:id>/', views.delete,name= "delete"), 
    path('nicks/', views.nicks,name= "nicks"),  
    path('comment/<int:id>',views.addComment,name = "comment"),
]

whoseitem1/urls.py
from django.contrib import admin
from django.urls import path,include
from nick import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name= "index"),  
    path('about/', views.about,name= "about"), 
    path('nick/', include("nick.urls")), 
    path('user/', include("user.urls")),      
    path('kontenjan/', include("kontenjan.urls")), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kontenjan/models.py
from pickle import FALSE
from django.db import models

# Create your models here.
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Kontenjan(models.Model):

    tip = models.CharField(max_length=100,blank=False)
    kodu = models.CharField(max_length = 10)
    sbkodu = models.CharField(max_length = 7)
    kurumadı = models.CharField(max_length = 70)
    sehir = models.CharField(max_length = 17)
    sayi = models.CharField(max_length = 17) 

    class Meta:
        abstract = True
        
    def __str__(self):
        return 'Tip: {0} Kurum Adı: {1}'.format(self.tip, self.kurumadı)

class Ebe(Kontenjan):
    pass

class Hemsire(Kontenjan):
    pass






"""class Comment(models.Model):
    nick = models.ForeignKey(Kontenjan,on_delete = models.CASCADE,verbose_name = "Makale",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200,verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']
"""

nick/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Nick(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar ")
    title = models.CharField(max_length = 17,verbose_name = "Server ")
    """content = models.CharField(max_length = 20,verbose_name = "Nick ") """
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin")
    def __str__(self):
        return self.title
    class Meta:
       ordering = ['-created_date']

class Comment(models.Model):
    nick = models.ForeignKey(Nick,on_delete = models.CASCADE,verbose_name = "Makale",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200,verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

kontenjan/forms.py
from django import forms
from .models import *

class EbeForm(forms.ModelForm):
    class Meta:
        model = Ebe
        fields = ('tip', 'kodu', 'sbkodu', 'kurumadı','sehir','sayi')


class HemsireForm(forms.ModelForm):
    class Meta:
        model = Hemsire
        fields = ('tip', 'kodu', 'sbkodu', 'kurumadı','sehir','sayi')

nick/forms.py
from django import forms 
from .models import Nick,Comment 


class NickForm(forms.ModelForm):
    class Meta:
        model = Nick
        fields = ["title","content","article_image"]

kontenjan/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse


from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
def kontenjan(request):


    return render(request,"kontenjan.html")

def ebe21(request):
    items = Ebe.objects.all()
    context = {
        'items': items,
        'header':'Ebelik Bölümü 2021',

    }

    return render(request,"kontenjan.html",context)

def hemsire21(request):
    items = Hemsire.objects.all()
    context = {
        'items': items,
        'header':'Hemsire Bölümü 2021',

    }

    return render(request,"kontenjan.html",context)

nick/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse

import nick
from .forms import NickForm
from .models import Nick,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):

    keyword = request.GET.get("keyword")

    if keyword :
        articles = Nick.objects.filter(title__contains = keyword)
        return render(request,"index.html",{"articles":articles})

    articles = Nick.objects.filter()
    context = {
        "articles" : articles
    }
    return render(request,"index.html",context)


def about(request):
    return render(request,"about.html")

@login_required(login_url="user:login")
def dashboard(request):
    form = Nick.objects.filter(author=request.user)
    context = {
        "form" : form
    }
    return render(request,"dashboard.html",context)
@login_required(login_url="user:login")
def addnick(request):
    form = NickForm(request.POST or None,request.FILES or None)
    context = {
            "form" : form
        }

    if form.is_valid():
        nick = form.save(commit=False)
        
        nick.author = request.user
        nick.save()

        messages.success(request,"Makale başarıyla oluşturuldu")
        return redirect("nick:dashboard")

        
    return render(request,"addnick.html",context)

@login_required(login_url="user:login")
def detail(request,id):
    nick = get_object_or_404(Nick,id=id)
    comments = nick.comments.all()
    print(comments)
    return render(request,"detail.html",{"nick":nick,"comments":comments})


@login_required(login_url="user:login")
def update(request,id):

    form = get_object_or_404(Nick,id=id)

    form = NickForm(request.POST or None,request.FILES or None,instance = form)
    if form.is_valid():
        nick = form.save(commit=False)
        
        nick.author = request.user
        nick.save()

        messages.success(request,"Makale başarıyla güncellendi")
        return redirect("index")
    
    return render(request,"update.html",{"form":form})  
@login_required(login_url="user:login")
def delete(request,id):

    form = get_object_or_404(Nick,id=id)
    form.delete()

    messages.success(request,"Makale başarıyla silindi")

    
    return redirect("nick:dashboard")

@login_required(login_url="user:login")
def nicks(request):
    keyword = request.GET.get("keyword")

    if keyword :
        articles = Nick.objects.filter(title__contains = keyword)
        return render(request,"nicks.html",{"articles":articles})

    articles = Nick.objects.filter()
    context = {
        "articles" : articles
    }
    return render(request,"nicks.html",context)


def addComment(request,id):
    nick = get_object_or_404(Nick,id = id)

    if request.method == "POST":
        comment_author = request.user
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)

        newComment.nick = nick

        newComment.save()
    return redirect(reverse("nick:detail",kwargs={"id":id}))
    

templates/about.html
{% extends 'layout.html' %}


{% block body %}
<div style= "margin-top : 100px;" class="jumbotron text-center">
<br><br>
    <p>Hakkımda</p> </div>
{% endblock  %}

templates/addnick.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">

        <h2>Nick Ekleme Ekranı</h2> 
        <hr>
        <p>Eklemek istediğiniz nickleri giriniz, <small>{{request.user.username}} </small></p>  <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Nick Ekle</button>
        </form>
    </div>
</div>
        
{% endblock  %}

templates/dashboard.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">

        <h2>Kontrol Paneli</h2> 
        <hr>
        <p>Hoşgeldiniz, <small>{{request.user.username}} </small></p>  <hr>
    <a href="/nick/addnick">
            <button>Nick Ekle</button>
        </a>  <hr>


            {% if form %}
            <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Başlık</th>
                        <th scope="col">Yazar</th>
                        <th scope="col">Tarih</th>
                        <th scope="col">Güncelle</th>
                        <th scope="col">Sil</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for nick in form %}
                    <tr>
                        <th scope="row">{{nick.id}}</th>
                        <td><a href="{% url 'nick:detail' nick.id %}">{{nick.title}}</a></td>
                        <td>{{nick.author.username}}</td>
                        <td>{{nick.created_date}}</td>
                        <td><a href="{% url 'nick:update' nick.id %}" class = "btn btn-danger">Güncelle</a></td>
                        <td><a href="{% url 'nick:delete' nick.id %}" class = "btn btn-danger">Sil</a> </td>
                        
                    </tr>
                    {% endfor %}
                    
                    </tbody>
                </table>
            {% else %}
            
            <div class = "alert alert-danger">
                Henüz bir makaleniz bulunmuyor...
            
            </div>
            {% endif %}
            

            <br>


    </div>
</div>
        
{% endblock  %}

templates/detail.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}

 <!-- Post Content Column -->
 <div class="col-lg-8">

    <!-- Title -->
    <h3 class="mt-4">{{nick.title}}</h3>

    <!-- Author -->
    <p class="lead">
      
      {{nick.author.username}} tarafından yayınlandı
    </p>

    <hr>

    <!--Date/Time -->
    <p>{{nick.created_date}}</p>

    <hr>

    <!--  Preview Image  -->
    {% if nick.article_image %}
    <img class="img-fluid rounded" src="{{form.article_image.url}}" alt="">
    {% endif %} 
   

    <hr>

    <!-- Post Content -->
    <p class="lead">
        {{nick.content|safe}}
    </p>

    <h4>Yorumlar</h4>
    <hr>
    {% if comments %}
    {% for comment in comments  %}
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">  <hr>
          <h5 class="mt-0">{{comment.comment_author}}</h5>
          {{comment.comment_date}} <br>
          {{comment.comment_content}}
        </div>
      </div>
    {% endfor %}
    
    
    {% else %}
    <div class ="alert alert-danger">
      Bu makaleye herhangi bir yorum yazılmamış,ilk yorum yapan siz olun!
    </div>
    {% endif %}
    
    <hr>
    <div class="card my-4">
      <h5 class="card-header">Yorum Ekle:</h5>
      <div class="card-body">
        <form method = "post" action = "{% url 'nick:comment' nick.id %}">
          {% csrf_token %}
          <div class="form-group">
            <p><small>{{request.user.username}} olarak yorum yapıyorsunuz. </small></p>

            </div>
          <div class="form-group">
              <label for="formGroupExampleInput">Yorum</label>
            <textarea name = "comment_content" class="form-control" rows="3"></textarea>
          </div>
          <button type="submit" class="btn btn-danger">Ekle</button>
        </form>
      </div>
    </div>
</div>

        
{% endblock body %}

templates/index.html
{% extends 'layout.html' %}


{% block body %}
<div style= "margin-top : 100px;" class="jumbotron text-center">
<br><br>  
    <p>Ana Sayfa</p>
</div>

{% if request.user.is_authenticated %}
    Giriş Yapılmış {{request.user.username}}
{% else %}
    Giriş yapılmamış 
{% endif %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        <h2>Kayıtlı Nickler</h2> 
        <hr>
        <p>Hoşgeldiniz, <small>{{request.user.username}} </small></p> 

        <form>
            {% csrf_token %} 
           <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
         <button type="submit" class="btn btn-danger">Ara</button>
       </form>

            {% if articles %}
            <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Başlık</th>
                        <th scope="col">Yazar</th>
                        <th scope="col">Tarih</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for article  in articles %}
                    <tr>
                        <th scope="row">{{article.id}}</th>
                        <td><a href="{% url 'nick:detail' article.id %}">{{article.title}}</a></td> 
                        <td>{{article.author.username}}</td>
                        <td>{{article.created_date}}</td>

                        
                    </tr>
                    {% endfor %}
                    
                    </tbody>
                </table>
            {% else %}
            
            <div class = "alert alert-danger">
                Nick Bulunamadı
            
            </div>
            {% endif %}
            

            <br>


    </div>
</div>

{% endblock  %}

templates/kontenjan.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        <div>

            <h4>{{ header }} Kontenjanları</h4>
          </div>
        <table class="table table-hover">
            <thead>
              <tr>
                <th></th>
                <th>Kodu</th>
                <th>Sb Kodu</th>
                <th>Kurum</th>
                <th>Şehir</th>
                <th>Kontenjan</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
        
              {% for item in items %}
        
              <tr>
                
                <td>{{ item.tip }}
                <td>{{ item.kodu }}</td>
                <td>{{ item.sbkodu }} </td>
                <td>{{ item.kurumadı }}</td>
                <td>{{ item.sehir }}</td>
                <td>{{ item.sayi }}</td>

        
        
              </tr>
        
              {% endfor %}
            </tbody>
          </table>


    </div>
  </div>


{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
 
  <!--  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Whose İtem</title>

</head>
<body>
    <br>
    {% include "includes/navbar.html" %}

        

    <div style = "margin-top : 100px; margin-bottom:100px;" class = "container">
            
        {% if messages %}
            
                {% for message in messages %}
                {% if message.tags == "info" %}
                <div class="alert alert-danger">{{ message }}</div>
                {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                {% endif %}


                {% endfor %}
            
            {% endif %}
        {% block body %}
        
        {% endblock body %}
    
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>


</body>
</html>

templates/login.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
    <br><br>
        <p>Giriş Yap</p> 
        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Giriş Yap</button>
        </form>
    </div>
</div>
        
{% endblock  %}

templates/nicks.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">

        <h2>Kayıtlı Nickler</h2> 
        <hr>
        <p>Hoşgeldiniz, <small>{{request.user.username}} </small></p> 

        <form>
            {% csrf_token %} 
           <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
         <button type="submit" class="btn btn-danger">Ara</button>
       </form>

            {% if articles %}
            <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Başlık</th>
                        <th scope="col">Yazar</th>
                        <th scope="col">Tarih</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for article  in articles %}
                    <tr>
                        <th scope="row">{{article.id}}</th>
                        <td><a href="{% url 'nick:detail' article.id %}">{{article.title}}</a></td>
                        <td>{{article.author.username}}</td>
                        <td>{{article.created_date}}</td>

                        
                    </tr>
                    {% endfor %}
                    
                    </tbody>
                </table>
            {% else %}
            
            <div class = "alert alert-danger">
                Nick Bulunamadı
            
            </div>
            {% endif %}
            

            <br>


    </div>
</div>
        
{% endblock  %}

templates/register.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}


{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <br><br>
            <p>Kayıt Ol</p> 

    <form method = "post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type = "submit" class = "btn btn-danger">Kayıt Ol</button>
    </form>
    </div>
</div>

{% endblock  %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Nick Güncelle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Nick Güncelle</button>
        </form>
    </div>
  </div>


{% endblock body %}